-- Run this in Supabase SQL Editor if these tables do not already exist.
-- RLS is enabled. Replace YOUR_ADMIN_USER_UUID with the UUID of your admin Auth user.

create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price numeric,
  seats integer,
  image_url text,
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists public.routes (
  id bigint generated by default as identity primary key,
  from_city text not null,
  to_city text not null,
  distance text,
  duration text,
  one_way_price numeric,
  round_trip_price numeric,
  created_at timestamptz default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  icon text,
  status text default 'active',
  created_at timestamptz default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  city text,
  rating integer,
  review text,
  created_at timestamptz default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  customer_name text,
  phone text,
  from_city text,
  to_city text,
  trip_type text,
  passengers integer,
  status text default 'new',
  booking_date timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  business_name text,
  phone text,
  whatsapp text,
  email text,
  address text,
  hero_image_url text,
  hero_title text,
  hero_description text,
  about_text text,
  created_at timestamptz default now()
);

alter table public.cars enable row level security;
alter table public.routes enable row level security;
alter table public.services enable row level security;
alter table public.reviews enable row level security;
alter table public.bookings enable row level security;
alter table public.settings enable row level security;

-- IMPORTANT:
-- These policies are for a small private admin setup. For production,
-- restrict write policies to your admin user's auth.uid().
create policy if not exists "authenticated manage cars" on public.cars for all to authenticated using (true) with check (true);
create policy if not exists "authenticated manage routes" on public.routes for all to authenticated using (true) with check (true);
create policy if not exists "authenticated manage services" on public.services for all to authenticated using (true) with check (true);
create policy if not exists "authenticated manage reviews" on public.reviews for all to authenticated using (true) with check (true);
create policy if not exists "authenticated manage bookings" on public.bookings for all to authenticated using (true) with check (true);
create policy if not exists "authenticated manage settings" on public.settings for all to authenticated using (true) with check (true);
