const login=document.getElementById("login"),app=document.getElementById("app"),loginMsg=document.getElementById("loginMsg");
async function init(){const {data}=await supabaseClient.auth.getSession(); if(data.session) showApp();}
function showApp(){login.hidden=true;app.hidden=false;loadCars();}
document.getElementById("loginForm").addEventListener("submit",async e=>{e.preventDefault();const {error}=await supabaseClient.auth.signInWithPassword({email:email.value,password:password.value});if(error)loginMsg.textContent=error.message;else showApp();});
document.getElementById("logout").onclick=async()=>{await supabaseClient.auth.signOut();location.reload();};
const list=document.getElementById("carsList"),editor=document.getElementById("carEditor");
async function loadCars(){const {data,error}=await supabaseClient.from("cars").select("*").order("created_at",{ascending:false});if(error){list.textContent=error.message;return;}list.innerHTML=data.length?data.map(c=>`<div class="car-row"><img src="${esc(c.image_url||"../images/hero-car.svg")}"><div><h3>${esc(c.name)}</h3><p>${esc(c.category||"")} · ${c.price_per_km?`₹${c.price_per_km}/km`:"Price on request"} · ${c.active?"Visible":"Hidden"}</p></div><div class="row-actions"><button onclick='editCar(${JSON.stringify(c).replace(/'/g,"&#39;")})'>Edit</button><button onclick="deleteCar('${c.id}')">Delete</button></div></div>`).join(""):'<p>No cars yet. Add your first car.</p>';}
function editCar(c){editor.hidden=false;document.getElementById("editorTitle").textContent="Edit car";carId.value=c.id;carName.value=c.name||"";carCategory.value=c.category||"";carPrice.value=c.price_per_km||"";carSeats.value=c.seats||"";carLuggage.value=c.luggage||"";carImage.value=c.image_url||"";carFeatures.value=(c.features||[]).join(", ");carActive.checked=c.active!==false;scrollTo({top:editor.offsetTop-20,behavior:"smooth"});}
document.getElementById("newCar").onclick=()=>{document.getElementById("carForm").reset();carId.value="";carActive.checked=true;document.getElementById("editorTitle").textContent="Add car";editor.hidden=false;};
document.getElementById("cancel").onclick=()=>editor.hidden=true;
document.getElementById("carForm").addEventListener("submit",async e=>{e.preventDefault();const payload={name:carName.value.trim(),category:carCategory.value.trim(),price_per_km:carPrice.value?Number(carPrice.value):null,seats:carSeats.value?Number(carSeats.value):null,luggage:carLuggage.value.trim(),image_url:carImage.value.trim()||null,features:carFeatures.value.split(",").map(x=>x.trim()).filter(Boolean),active:carActive.checked};let res=carId.value?await supabaseClient.from("cars").update(payload).eq("id",carId.value):await supabaseClient.from("cars").insert(payload);if(res.error){carMsg.textContent=res.error.message;return;}editor.hidden=true;loadCars();});
async function deleteCar(id){if(!confirm("Delete this car?"))return;const {error}=await supabaseClient.from("cars").delete().eq("id",id);if(error)alert(error.message);else loadCars();}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");carsTab.hidden=t.dataset.tab!=="cars";infoTab.hidden=t.dataset.tab!=="info";});
init();
